"""centralized_notifications_and_chat

Revision ID: 063a4d300d6a
Revises: 8775f17136e6
Create Date: 2026-07-10 13:56:33.398782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '063a4d300d6a'
down_revision: Union[str, Sequence[str], None] = '8775f17136e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('attachment_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_custom_attributes', 'messages', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_custom_attributes', 'notifications', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('message_mentions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('mentioned_user_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_mentions_custom_attributes', 'message_mentions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('message_read_receipts',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_read_receipts_custom_attributes', 'message_read_receipts', ['custom_attributes'], unique=False, postgresql_using='gin')
    
    # --- Data Migration ---
    op.execute("""
        INSERT INTO messages (id, entity_type, entity_id, sender_id, content, attachment_url, attachment_name, created_at, updated_at, custom_attributes)
        SELECT id, 'quotation', quotation_id, sender_id, content, attachment_url, attachment_name, created_at, updated_at, custom_attributes
        FROM quotation_messages;
    """)
    op.execute("""
        INSERT INTO message_mentions (id, message_id, mentioned_user_id, is_read, custom_attributes)
        SELECT id, message_id, mentioned_user_id, is_read, custom_attributes
        FROM quotation_message_mentions;
    """)
    op.execute("""
        INSERT INTO message_read_receipts (id, message_id, user_id, read_at, custom_attributes)
        SELECT id, message_id, user_id, read_at, custom_attributes
        FROM quotation_message_read_receipts;
    """)
    # -----------------------

    op.drop_index(op.f('idx_quotation_message_mentions_custom_attributes'), table_name='quotation_message_mentions', postgresql_using='gin')
    op.drop_table('quotation_message_mentions')
    op.drop_index(op.f('idx_quotation_message_read_receipts_custom_attributes'), table_name='quotation_message_read_receipts', postgresql_using='gin')
    op.drop_table('quotation_message_read_receipts')
    op.drop_index(op.f('idx_quotation_messages_custom_attributes'), table_name='quotation_messages', postgresql_using='gin')
    op.drop_table('quotation_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_message_mentions',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mentioned_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], name=op.f('quotation_message_mentions_mentioned_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['quotation_messages.id'], name=op.f('quotation_message_mentions_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quotation_message_mentions_pkey'))
    )
    op.create_index(op.f('idx_quotation_message_mentions_custom_attributes'), 'quotation_message_mentions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('quotation_message_read_receipts',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['quotation_messages.id'], name=op.f('quotation_message_read_receipts_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quotation_message_read_receipts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quotation_message_read_receipts_pkey'))
    )
    op.create_index(op.f('idx_quotation_message_read_receipts_custom_attributes'), 'quotation_message_read_receipts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('quotation_messages',
    sa.Column('quotation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attachment_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachment_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('quotation_messages_quotation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('quotation_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quotation_messages_pkey'))
    )
    op.create_index(op.f('idx_quotation_messages_custom_attributes'), 'quotation_messages', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.drop_index('idx_message_read_receipts_custom_attributes', table_name='message_read_receipts', postgresql_using='gin')
    op.drop_table('message_read_receipts')
    op.drop_index('idx_message_mentions_custom_attributes', table_name='message_mentions', postgresql_using='gin')
    op.drop_table('message_mentions')
    op.drop_index('idx_notifications_custom_attributes', table_name='notifications', postgresql_using='gin')
    op.drop_table('notifications')
    op.drop_index('idx_messages_custom_attributes', table_name='messages', postgresql_using='gin')
    op.drop_table('messages')
    # ### end Alembic commands ###
