"""update contact model

Revision ID: 06f6ef514d6d
Revises: 2e575ab4144c
Create Date: 2026-06-25 10:19:27.700470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '06f6ef514d6d'
down_revision: Union[str, Sequence[str], None] = '2e575ab4144c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    contact_status_enum = sa.Enum('PASSIVE', 'OPEN', 'REPLIED', name='crm_contact_status')
    contact_status_enum.create(op.get_bind())
    op.add_column('crm_contacts', sa.Column('status', contact_status_enum, nullable=False, server_default='PASSIVE'))
    op.alter_column('crm_contacts', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_contacts', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('crm_contacts', 'status')
    op.execute('DROP TYPE crm_contact_status')
    # ### end Alembic commands ###
