"""add_stock_entry_and_advanced_masters

Revision ID: 12b42827474a
Revises: 17b45f53a21a
Create Date: 2026-06-25 02:26:48.862975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b42827474a'
down_revision: Union[str, Sequence[str], None] = '17b45f53a21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_shipping_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_shipping_rules_custom_attributes', 'inv_shipping_rules', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_shipping_rules_name'), 'inv_shipping_rules', ['name'], unique=True)
    op.create_table('inv_stock_entries',
    sa.Column('series', sa.String(length=100), nullable=False),
    sa.Column('entry_type', sa.Enum('MATERIAL_RECEIPT', 'MATERIAL_ISSUE', 'MATERIAL_TRANSFER', 'MANUFACTURE', name='inv_stock_entry_type'), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('posting_time', sa.Time(), nullable=False),
    sa.Column('default_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', name='inv_stock_entry_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_stock_entries_custom_attributes', 'inv_stock_entries', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_item_alternatives',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('alternative_item_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['alternative_item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_item_alternatives_custom_attributes', 'inv_item_alternatives', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_item_alternatives_alternative_item_id'), 'inv_item_alternatives', ['alternative_item_id'], unique=False)
    op.create_index(op.f('ix_inv_item_alternatives_item_id'), 'inv_item_alternatives', ['item_id'], unique=False)
    op.create_table('inv_item_manufacturers',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer_part_no', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_item_manufacturers_custom_attributes', 'inv_item_manufacturers', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_item_manufacturers_item_id'), 'inv_item_manufacturers', ['item_id'], unique=False)
    op.create_table('inv_stock_entry_details',
    sa.Column('stock_entry_id', sa.UUID(), nullable=False),
    sa.Column('source_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('target_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('basic_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_entry_id'], ['inv_stock_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_warehouse_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_stock_entry_details_custom_attributes', 'inv_stock_entry_details', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_stock_entry_details_stock_entry_id'), 'inv_stock_entry_details', ['stock_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inv_stock_entry_details_stock_entry_id'), table_name='inv_stock_entry_details')
    op.drop_index('idx_inv_stock_entry_details_custom_attributes', table_name='inv_stock_entry_details', postgresql_using='gin')
    op.drop_table('inv_stock_entry_details')
    op.drop_index(op.f('ix_inv_item_manufacturers_item_id'), table_name='inv_item_manufacturers')
    op.drop_index('idx_inv_item_manufacturers_custom_attributes', table_name='inv_item_manufacturers', postgresql_using='gin')
    op.drop_table('inv_item_manufacturers')
    op.drop_index(op.f('ix_inv_item_alternatives_item_id'), table_name='inv_item_alternatives')
    op.drop_index(op.f('ix_inv_item_alternatives_alternative_item_id'), table_name='inv_item_alternatives')
    op.drop_index('idx_inv_item_alternatives_custom_attributes', table_name='inv_item_alternatives', postgresql_using='gin')
    op.drop_table('inv_item_alternatives')
    op.drop_index('idx_inv_stock_entries_custom_attributes', table_name='inv_stock_entries', postgresql_using='gin')
    op.drop_table('inv_stock_entries')
    op.drop_index(op.f('ix_inv_shipping_rules_name'), table_name='inv_shipping_rules')
    op.drop_index('idx_inv_shipping_rules_custom_attributes', table_name='inv_shipping_rules', postgresql_using='gin')
    op.drop_table('inv_shipping_rules')
    # ### end Alembic commands ###
