"""add_full_erpnext_procurement_and_inventory

Revision ID: 17b45f53a21a
Revises: e9dadb28356c
Create Date: 2026-06-25 01:15:25.322871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17b45f53a21a'
down_revision: Union[str, Sequence[str], None] = 'e9dadb28356c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proc_material_requests',
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False, comment='Date the request was raised'),
    sa.Column('required_by', sa.DateTime(timezone=True), nullable=True, comment='Date the material must be available'),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'Ordered', 'Received', 'Cancelled', name='proc_material_request_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_material_requests_custom_attributes', 'proc_material_requests', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('proc_suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=True, comment="Supplier classification group, e.g. 'Raw Material', 'Services'"),
    sa.Column('tax_id', sa.String(length=100), nullable=True, comment='VAT / GST / EIN registration number'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_suppliers_custom_attributes', 'proc_suppliers', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_proc_suppliers_name'), 'proc_suppliers', ['name'], unique=True)
    op.create_index(op.f('ix_proc_suppliers_tax_id'), 'proc_suppliers', ['tax_id'], unique=False)
    op.create_table('proc_purchase_orders',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'Received', 'Cancelled', name='proc_purchase_order_status'), nullable=False),
    sa.Column('material_request_id', sa.UUID(), nullable=True, comment='Optional reference back to the originating MaterialRequest'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['material_request_id'], ['proc_material_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['proc_suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_purchase_orders_custom_attributes', 'proc_purchase_orders', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_proc_purchase_orders_material_request_id'), 'proc_purchase_orders', ['material_request_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_orders_supplier_id'), 'proc_purchase_orders', ['supplier_id'], unique=False)
    op.create_table('proc_material_request_items',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['proc_material_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_material_request_items_custom_attributes', 'proc_material_request_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_proc_material_request_items_item_id'), 'proc_material_request_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_proc_material_request_items_request_id'), 'proc_material_request_items', ['request_id'], unique=False)
    op.create_index(op.f('ix_proc_material_request_items_warehouse_id'), 'proc_material_request_items', ['warehouse_id'], unique=False)
    op.create_table('proc_purchase_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['proc_purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_purchase_order_items_custom_attributes', 'proc_purchase_order_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_proc_purchase_order_items_item_id'), 'proc_purchase_order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_order_items_order_id'), 'proc_purchase_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_order_items_warehouse_id'), 'proc_purchase_order_items', ['warehouse_id'], unique=False)
    op.create_table('proc_purchase_invoices',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_receipt_id', sa.UUID(), nullable=True, comment='GRN this invoice is raised against'),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'Paid', 'Cancelled', name='proc_invoice_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['purchase_receipt_id'], ['proc_purchase_receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['proc_suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_purchase_invoices_custom_attributes', 'proc_purchase_invoices', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_proc_purchase_invoices_purchase_receipt_id'), 'proc_purchase_invoices', ['purchase_receipt_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_invoices_supplier_id'), 'proc_purchase_invoices', ['supplier_id'], unique=False)
    op.add_column('proc_purchase_receipt_items', sa.Column('purchase_order_item_id', sa.UUID(), nullable=True, comment='Link to the originating PO line for over/under-receipt tracking'))
    op.create_index(op.f('ix_proc_purchase_receipt_items_item_id'), 'proc_purchase_receipt_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_receipt_items_purchase_order_item_id'), 'proc_purchase_receipt_items', ['purchase_order_item_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_receipt_items_receipt_id'), 'proc_purchase_receipt_items', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_receipt_items_warehouse_id'), 'proc_purchase_receipt_items', ['warehouse_id'], unique=False)
    op.drop_constraint(op.f('proc_purchase_receipt_items_warehouse_id_fkey'), 'proc_purchase_receipt_items', type_='foreignkey')
    op.create_foreign_key(None, 'proc_purchase_receipt_items', 'proc_purchase_order_items', ['purchase_order_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'proc_purchase_receipt_items', 'inv_warehouses', ['warehouse_id'], ['id'], ondelete='RESTRICT')
    op.add_column('proc_purchase_receipts', sa.Column('purchase_order_id', sa.UUID(), nullable=True, comment='Optional link to the originating Purchase Order'))
    op.create_index(op.f('ix_proc_purchase_receipts_purchase_order_id'), 'proc_purchase_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_proc_purchase_receipts_supplier_id'), 'proc_purchase_receipts', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'proc_purchase_receipts', 'proc_purchase_orders', ['purchase_order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'proc_purchase_receipts', 'proc_suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proc_purchase_receipts', type_='foreignkey')
    op.drop_constraint(None, 'proc_purchase_receipts', type_='foreignkey')
    op.drop_index(op.f('ix_proc_purchase_receipts_supplier_id'), table_name='proc_purchase_receipts')
    op.drop_index(op.f('ix_proc_purchase_receipts_purchase_order_id'), table_name='proc_purchase_receipts')
    op.drop_column('proc_purchase_receipts', 'purchase_order_id')
    op.drop_constraint(None, 'proc_purchase_receipt_items', type_='foreignkey')
    op.drop_constraint(None, 'proc_purchase_receipt_items', type_='foreignkey')
    op.create_foreign_key(op.f('proc_purchase_receipt_items_warehouse_id_fkey'), 'proc_purchase_receipt_items', 'inv_warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proc_purchase_receipt_items_warehouse_id'), table_name='proc_purchase_receipt_items')
    op.drop_index(op.f('ix_proc_purchase_receipt_items_receipt_id'), table_name='proc_purchase_receipt_items')
    op.drop_index(op.f('ix_proc_purchase_receipt_items_purchase_order_item_id'), table_name='proc_purchase_receipt_items')
    op.drop_index(op.f('ix_proc_purchase_receipt_items_item_id'), table_name='proc_purchase_receipt_items')
    op.drop_column('proc_purchase_receipt_items', 'purchase_order_item_id')
    op.drop_index(op.f('ix_proc_purchase_invoices_supplier_id'), table_name='proc_purchase_invoices')
    op.drop_index(op.f('ix_proc_purchase_invoices_purchase_receipt_id'), table_name='proc_purchase_invoices')
    op.drop_index('idx_proc_purchase_invoices_custom_attributes', table_name='proc_purchase_invoices', postgresql_using='gin')
    op.drop_table('proc_purchase_invoices')
    op.drop_index(op.f('ix_proc_purchase_order_items_warehouse_id'), table_name='proc_purchase_order_items')
    op.drop_index(op.f('ix_proc_purchase_order_items_order_id'), table_name='proc_purchase_order_items')
    op.drop_index(op.f('ix_proc_purchase_order_items_item_id'), table_name='proc_purchase_order_items')
    op.drop_index('idx_proc_purchase_order_items_custom_attributes', table_name='proc_purchase_order_items', postgresql_using='gin')
    op.drop_table('proc_purchase_order_items')
    op.drop_index(op.f('ix_proc_material_request_items_warehouse_id'), table_name='proc_material_request_items')
    op.drop_index(op.f('ix_proc_material_request_items_request_id'), table_name='proc_material_request_items')
    op.drop_index(op.f('ix_proc_material_request_items_item_id'), table_name='proc_material_request_items')
    op.drop_index('idx_proc_material_request_items_custom_attributes', table_name='proc_material_request_items', postgresql_using='gin')
    op.drop_table('proc_material_request_items')
    op.drop_index(op.f('ix_proc_purchase_orders_supplier_id'), table_name='proc_purchase_orders')
    op.drop_index(op.f('ix_proc_purchase_orders_material_request_id'), table_name='proc_purchase_orders')
    op.drop_index('idx_proc_purchase_orders_custom_attributes', table_name='proc_purchase_orders', postgresql_using='gin')
    op.drop_table('proc_purchase_orders')
    op.drop_index(op.f('ix_proc_suppliers_tax_id'), table_name='proc_suppliers')
    op.drop_index(op.f('ix_proc_suppliers_name'), table_name='proc_suppliers')
    op.drop_index('idx_proc_suppliers_custom_attributes', table_name='proc_suppliers', postgresql_using='gin')
    op.drop_table('proc_suppliers')
    op.drop_index('idx_proc_material_requests_custom_attributes', table_name='proc_material_requests', postgresql_using='gin')
    op.drop_table('proc_material_requests')
    # ### end Alembic commands ###
