"""Add Sales Phase B tables

Revision ID: 1c40e8b45680
Revises: d78f4fa8836d
Create Date: 2026-07-07 22:51:09.090247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c40e8b45680'
down_revision: Union[str, Sequence[str], None] = 'd78f4fa8836d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_lists_custom_attributes', 'price_lists', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('product_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_categories_custom_attributes', 'product_categories', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('quotation_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template_file', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotation_templates_custom_attributes', 'quotation_templates', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('products',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=False),
    sa.Column('standard_price', sa.Float(), nullable=False),
    sa.Column('min_order_qty', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_products_custom_attributes', 'products', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('price_list_items',
    sa.Column('price_list_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_list_items_custom_attributes', 'price_list_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('product_attachments',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_attachments_custom_attributes', 'product_attachments', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('quotations',
    sa.Column('quotation_number', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_quotation_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validity_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('delivery_terms', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('overall_discount_type', sa.String(), nullable=True),
    sa.Column('overall_discount_value', sa.Float(), nullable=False),
    sa.Column('overall_discount_amount', sa.Float(), nullable=False),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('quotation_type', sa.String(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('prepared_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['quotation_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_number')
    )
    op.create_index('idx_quotations_custom_attributes', 'quotations', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('quotation_line_items',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_discount_type', sa.String(), nullable=True),
    sa.Column('line_discount_value', sa.Float(), nullable=False),
    sa.Column('line_discount_amount', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotation_line_items_custom_attributes', 'quotation_line_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('sales_orders',
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('delivery_terms', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('overall_discount_amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('idx_sales_orders_custom_attributes', 'sales_orders', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('sales_order_line_items',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_order_line_items_custom_attributes', 'sales_order_line_items', ['custom_attributes'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_sales_order_line_items_custom_attributes', table_name='sales_order_line_items', postgresql_using='gin')
    op.drop_table('sales_order_line_items')
    op.drop_index('idx_sales_orders_custom_attributes', table_name='sales_orders', postgresql_using='gin')
    op.drop_table('sales_orders')
    op.drop_index('idx_quotation_line_items_custom_attributes', table_name='quotation_line_items', postgresql_using='gin')
    op.drop_table('quotation_line_items')
    op.drop_index('idx_quotations_custom_attributes', table_name='quotations', postgresql_using='gin')
    op.drop_table('quotations')
    op.drop_index('idx_product_attachments_custom_attributes', table_name='product_attachments', postgresql_using='gin')
    op.drop_table('product_attachments')
    op.drop_index('idx_price_list_items_custom_attributes', table_name='price_list_items', postgresql_using='gin')
    op.drop_table('price_list_items')
    op.drop_index('idx_products_custom_attributes', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_index('idx_quotation_templates_custom_attributes', table_name='quotation_templates', postgresql_using='gin')
    op.drop_table('quotation_templates')
    op.drop_index('idx_product_categories_custom_attributes', table_name='product_categories', postgresql_using='gin')
    op.drop_table('product_categories')
    op.drop_index('idx_price_lists_custom_attributes', table_name='price_lists', postgresql_using='gin')
    op.drop_table('price_lists')
    # ### end Alembic commands ###
