"""Add finance tables

Revision ID: 2e575ab4144c
Revises: 12b42827474a
Create Date: 2026-06-25 06:45:51.928822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e575ab4144c'
down_revision: Union[str, Sequence[str], None] = '12b42827474a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_banks',
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('swift_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_banks_custom_attributes', 'fin_banks', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_budgets',
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('fiscal_year', sa.String(length=20), nullable=False),
    sa.Column('total_allocation', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('amount_spent', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_budgets_custom_attributes', 'fin_budgets', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_shareholders',
    sa.Column('shareholder_name', sa.String(length=255), nullable=False),
    sa.Column('share_type', sa.String(length=100), nullable=False),
    sa.Column('total_shares', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('equity_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_shareholders_custom_attributes', 'fin_shareholders', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_tax_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_fin_tax_categories_custom_attributes', 'fin_tax_categories', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_delivery_notes',
    sa.Column('series', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('posting_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_delivery_notes_custom_attributes', 'inv_delivery_notes', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_pick_lists',
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_pick_lists_custom_attributes', 'inv_pick_lists', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_bank_accounts',
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('linked_gl_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['fin_banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_gl_account_id'], ['fin_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index('idx_fin_bank_accounts_custom_attributes', 'fin_bank_accounts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_invoices',
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='fin_invoice_status'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['fin_journal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_invoices_custom_attributes', 'fin_invoices', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_fin_invoices_invoice_number'), 'fin_invoices', ['invoice_number'], unique=True)
    op.create_table('fin_payments',
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='fin_payment_status'), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['fin_journal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index('idx_fin_payments_custom_attributes', 'fin_payments', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_share_transfers',
    sa.Column('shareholder_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('number_of_shares', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['fin_journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shareholder_id'], ['fin_shareholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_share_transfers_custom_attributes', 'fin_share_transfers', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_tax_rules',
    sa.Column('tax_category_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tax_category_id'], ['fin_tax_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_tax_rules_custom_attributes', 'fin_tax_rules', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_delivery_note_details',
    sa.Column('delivery_note_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['inv_delivery_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_delivery_note_details_custom_attributes', 'inv_delivery_note_details', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_pick_list_items',
    sa.Column('pick_list_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('picked_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['pick_list_id'], ['inv_pick_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_pick_list_items_custom_attributes', 'inv_pick_list_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_bank_transactions',
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'FEE', name='fin_transaction_type'), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['fin_bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['fin_journal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_bank_transactions_custom_attributes', 'fin_bank_transactions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['fin_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_invoice_items_custom_attributes', 'fin_invoice_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_payment_reconciliations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['fin_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['fin_payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_payment_reconciliations_custom_attributes', 'fin_payment_reconciliations', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_purchase_tax_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_rule_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tax_rule_id'], ['fin_tax_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_fin_purchase_tax_templates_custom_attributes', 'fin_purchase_tax_templates', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_sales_tax_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_rule_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tax_rule_id'], ['fin_tax_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_fin_sales_tax_templates_custom_attributes', 'fin_sales_tax_templates', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_bank_clearance',
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLEARED', 'BOUNCED', name='fin_clearance_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['fin_bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['fin_payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_bank_clearance_custom_attributes', 'fin_bank_clearance', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('idx_hr_leave_requests_custom_attributes'), table_name='hr_leave_requests', postgresql_using='gin')
    op.drop_index(op.f('ix_hr_leave_requests_employee_id'), table_name='hr_leave_requests')
    op.drop_table('hr_leave_requests')
    op.drop_index(op.f('idx_hr_employee_records_custom_attributes'), table_name='hr_employee_records', postgresql_using='gin')
    op.drop_index(op.f('ix_hr_employee_records_hire_date'), table_name='hr_employee_records')
    op.drop_index(op.f('ix_hr_employee_records_user_id'), table_name='hr_employee_records')
    op.drop_table('hr_employee_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_employee_records',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('base_salary', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False),
    sa.Column('employment_status', postgresql.ENUM('ACTIVE', 'ON_LEAVE', 'TERMINATED', name='hr_employment_status'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('hr_employee_records_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_employee_records_pkey'))
    )
    op.create_index(op.f('ix_hr_employee_records_user_id'), 'hr_employee_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_hr_employee_records_hire_date'), 'hr_employee_records', ['hire_date'], unique=False)
    op.create_index(op.f('idx_hr_employee_records_custom_attributes'), 'hr_employee_records', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('hr_leave_requests',
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('SICK', 'VACATION', 'UNPAID', name='hr_leave_type'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('approval_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='hr_leave_approval_status'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee_records.id'], name=op.f('hr_leave_requests_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_leave_requests_pkey'))
    )
    op.create_index(op.f('ix_hr_leave_requests_employee_id'), 'hr_leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('idx_hr_leave_requests_custom_attributes'), 'hr_leave_requests', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.drop_index('idx_fin_bank_clearance_custom_attributes', table_name='fin_bank_clearance', postgresql_using='gin')
    op.drop_table('fin_bank_clearance')
    op.drop_index('idx_fin_sales_tax_templates_custom_attributes', table_name='fin_sales_tax_templates', postgresql_using='gin')
    op.drop_table('fin_sales_tax_templates')
    op.drop_index('idx_fin_purchase_tax_templates_custom_attributes', table_name='fin_purchase_tax_templates', postgresql_using='gin')
    op.drop_table('fin_purchase_tax_templates')
    op.drop_index('idx_fin_payment_reconciliations_custom_attributes', table_name='fin_payment_reconciliations', postgresql_using='gin')
    op.drop_table('fin_payment_reconciliations')
    op.drop_index('idx_fin_invoice_items_custom_attributes', table_name='fin_invoice_items', postgresql_using='gin')
    op.drop_table('fin_invoice_items')
    op.drop_index('idx_fin_bank_transactions_custom_attributes', table_name='fin_bank_transactions', postgresql_using='gin')
    op.drop_table('fin_bank_transactions')
    op.drop_index('idx_inv_pick_list_items_custom_attributes', table_name='inv_pick_list_items', postgresql_using='gin')
    op.drop_table('inv_pick_list_items')
    op.drop_index('idx_inv_delivery_note_details_custom_attributes', table_name='inv_delivery_note_details', postgresql_using='gin')
    op.drop_table('inv_delivery_note_details')
    op.drop_index('idx_fin_tax_rules_custom_attributes', table_name='fin_tax_rules', postgresql_using='gin')
    op.drop_table('fin_tax_rules')
    op.drop_index('idx_fin_share_transfers_custom_attributes', table_name='fin_share_transfers', postgresql_using='gin')
    op.drop_table('fin_share_transfers')
    op.drop_index('idx_fin_payments_custom_attributes', table_name='fin_payments', postgresql_using='gin')
    op.drop_table('fin_payments')
    op.drop_index(op.f('ix_fin_invoices_invoice_number'), table_name='fin_invoices')
    op.drop_index('idx_fin_invoices_custom_attributes', table_name='fin_invoices', postgresql_using='gin')
    op.drop_table('fin_invoices')
    op.drop_index('idx_fin_bank_accounts_custom_attributes', table_name='fin_bank_accounts', postgresql_using='gin')
    op.drop_table('fin_bank_accounts')
    op.drop_index('idx_inv_pick_lists_custom_attributes', table_name='inv_pick_lists', postgresql_using='gin')
    op.drop_table('inv_pick_lists')
    op.drop_index('idx_inv_delivery_notes_custom_attributes', table_name='inv_delivery_notes', postgresql_using='gin')
    op.drop_table('inv_delivery_notes')
    op.drop_index('idx_fin_tax_categories_custom_attributes', table_name='fin_tax_categories', postgresql_using='gin')
    op.drop_table('fin_tax_categories')
    op.drop_index('idx_fin_shareholders_custom_attributes', table_name='fin_shareholders', postgresql_using='gin')
    op.drop_table('fin_shareholders')
    op.drop_index('idx_fin_budgets_custom_attributes', table_name='fin_budgets', postgresql_using='gin')
    op.drop_table('fin_budgets')
    op.drop_index('idx_fin_banks_custom_attributes', table_name='fin_banks', postgresql_using='gin')
    op.drop_table('fin_banks')
    # ### end Alembic commands ###
