"""Add Collaboration Phase C tables

Revision ID: 40120f548624
Revises: 1c40e8b45680
Create Date: 2026-07-08 09:20:44.650063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40120f548624'
down_revision: Union[str, Sequence[str], None] = '1c40e8b45680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_messages',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('attachment_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotation_messages_custom_attributes', 'quotation_messages', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('quotation_message_mentions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('mentioned_user_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['quotation_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotation_message_mentions_custom_attributes', 'quotation_message_mentions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('quotation_message_read_receipts',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['quotation_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotation_message_read_receipts_custom_attributes', 'quotation_message_read_receipts', ['custom_attributes'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_quotation_message_read_receipts_custom_attributes', table_name='quotation_message_read_receipts', postgresql_using='gin')
    op.drop_table('quotation_message_read_receipts')
    op.drop_index('idx_quotation_message_mentions_custom_attributes', table_name='quotation_message_mentions', postgresql_using='gin')
    op.drop_table('quotation_message_mentions')
    op.drop_index('idx_quotation_messages_custom_attributes', table_name='quotation_messages', postgresql_using='gin')
    op.drop_table('quotation_messages')
    # ### end Alembic commands ###
