"""initial

Revision ID: 430dd2ff3953
Revises: 
Create Date: 2026-06-08 15:05:06.066822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430dd2ff3953'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_workspace_string', 'user_workspaces', ['user_id', 'workspace_string'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_workspace_string', 'user_workspaces', type_='unique')
    # ### end Alembic commands ###
