"""add_assets_and_allocation_history

Revision ID: 5ad02b6e84fc
Revises: 25f6d5f2a24a
Create Date: 2026-06-24 18:05:19.895098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ad02b6e84fc'
down_revision: Union[str, Sequence[str], None] = '25f6d5f2a24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_assets',
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_purchase_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Allocated', 'Maintenance', name='inv_asset_status'), nullable=False),
    sa.Column('allocated_to_user_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['allocated_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_assets_custom_attributes', 'inv_assets', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_assets_allocated_to_user_id'), 'inv_assets', ['allocated_to_user_id'], unique=False)
    op.create_index(op.f('ix_inv_assets_item_id'), 'inv_assets', ['item_id'], unique=False)
    op.create_index(op.f('ix_inv_assets_location_id'), 'inv_assets', ['location_id'], unique=False)
    op.create_index(op.f('ix_inv_assets_status'), 'inv_assets', ['status'], unique=False)
    op.create_table('inv_asset_allocation_history',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('allocated_to_user_id', sa.UUID(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['allocated_to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['inv_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_asset_allocation_history_custom_attributes', 'inv_asset_allocation_history', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_asset_allocation_history_allocated_at'), 'inv_asset_allocation_history', ['allocated_at'], unique=False)
    op.create_index(op.f('ix_inv_asset_allocation_history_allocated_to_user_id'), 'inv_asset_allocation_history', ['allocated_to_user_id'], unique=False)
    op.create_index(op.f('ix_inv_asset_allocation_history_asset_id'), 'inv_asset_allocation_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inv_asset_allocation_history_location_id'), 'inv_asset_allocation_history', ['location_id'], unique=False)
    op.create_index(op.f('ix_inv_asset_allocation_history_returned_at'), 'inv_asset_allocation_history', ['returned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inv_asset_allocation_history_returned_at'), table_name='inv_asset_allocation_history')
    op.drop_index(op.f('ix_inv_asset_allocation_history_location_id'), table_name='inv_asset_allocation_history')
    op.drop_index(op.f('ix_inv_asset_allocation_history_asset_id'), table_name='inv_asset_allocation_history')
    op.drop_index(op.f('ix_inv_asset_allocation_history_allocated_to_user_id'), table_name='inv_asset_allocation_history')
    op.drop_index(op.f('ix_inv_asset_allocation_history_allocated_at'), table_name='inv_asset_allocation_history')
    op.drop_index('idx_inv_asset_allocation_history_custom_attributes', table_name='inv_asset_allocation_history', postgresql_using='gin')
    op.drop_table('inv_asset_allocation_history')
    op.drop_index(op.f('ix_inv_assets_status'), table_name='inv_assets')
    op.drop_index(op.f('ix_inv_assets_location_id'), table_name='inv_assets')
    op.drop_index(op.f('ix_inv_assets_item_id'), table_name='inv_assets')
    op.drop_index(op.f('ix_inv_assets_allocated_to_user_id'), table_name='inv_assets')
    op.drop_index('idx_inv_assets_custom_attributes', table_name='inv_assets', postgresql_using='gin')
    op.drop_table('inv_assets')
    # ### end Alembic commands ###
