"""add_deal_module

Revision ID: 688fef6de371
Revises: b8a69636ef19
Create Date: 2026-07-10 11:05:23.632937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '688fef6de371'
down_revision: Union[str, Sequence[str], None] = 'b8a69636ef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_name', sa.String(), nullable=False),
    sa.Column('pipeline_stage', sa.String(), nullable=False),
    sa.Column('expected_revenue', sa.Float(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deals_custom_attributes', 'deals', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_foreign_key('fk_departments_manager_id_users', 'departments', 'users', ['manager_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('quotations', sa.Column('deal_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_quotations_deal_id_deals', 'quotations', 'deals', ['deal_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_record_shares_custom_attributes'), table_name='record_shares', postgresql_using='gin')
    # op.create_unique_constraint('uq_user_workspace_string', 'user_workspaces', ['user_id', 'workspace_string'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_workspace_string', 'user_workspaces', type_='unique')
    op.create_index(op.f('idx_record_shares_custom_attributes'), 'record_shares', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.drop_constraint('fk_quotations_deal_id_deals', 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'deal_id')
    op.drop_constraint('fk_departments_manager_id_users', 'departments', type_='foreignkey')
    op.drop_index('idx_deals_custom_attributes', table_name='deals', postgresql_using='gin')
    op.drop_table('deals')
    # ### end Alembic commands ###
