"""Initial V1 Beta architecture

Revision ID: 6bc3ade9d9e7
Revises: 430dd2ff3953
Create Date: 2026-06-08 15:12:06.091858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc3ade9d9e7'
down_revision: Union[str, Sequence[str], None] = '430dd2ff3953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_workspace_string', 'user_workspaces', ['user_id', 'workspace_string'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_workspace_string', 'user_workspaces', type_='unique')
    # ### end Alembic commands ###
