"""add_reference_numbers

Revision ID: 8775f17136e6
Revises: 688fef6de371
Create Date: 2026-07-10 11:47:29.064494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8775f17136e6'
down_revision: Union[str, Sequence[str], None] = '688fef6de371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE customer_seq START 1000")
    op.execute("CREATE SEQUENCE deal_seq START 1000")
    op.execute("CREATE SEQUENCE lead_seq START 1000")
    op.execute("CREATE SEQUENCE quotation_seq START 1000")
    op.execute("CREATE SEQUENCE sales_order_seq START 1000")

    op.add_column('customers', sa.Column('reference_number', sa.String(), server_default=sa.text("'CUST-' || nextval('customer_seq')"), nullable=False))
    op.create_unique_constraint('uq_customers_reference_number', 'customers', ['reference_number'])
    
    op.add_column('deals', sa.Column('reference_number', sa.String(), server_default=sa.text("'DEAL-' || nextval('deal_seq')"), nullable=False))
    op.create_unique_constraint('uq_deals_reference_number', 'deals', ['reference_number'])
    
    op.add_column('leads', sa.Column('reference_number', sa.String(), server_default=sa.text("'LEAD-' || nextval('lead_seq')"), nullable=False))
    op.create_unique_constraint('uq_leads_reference_number', 'leads', ['reference_number'])
    
    op.add_column('quotations', sa.Column('reference_number', sa.String(), server_default=sa.text("'QUO-' || nextval('quotation_seq')"), nullable=False))
    op.create_unique_constraint('uq_quotations_reference_number', 'quotations', ['reference_number'])
    
    op.add_column('sales_orders', sa.Column('reference_number', sa.String(), server_default=sa.text("'SO-' || nextval('sales_order_seq')"), nullable=False))
    op.create_unique_constraint('uq_sales_orders_reference_number', 'sales_orders', ['reference_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sales_orders_reference_number', 'sales_orders', type_='unique')
    op.drop_column('sales_orders', 'reference_number')
    op.drop_constraint('uq_quotations_reference_number', 'quotations', type_='unique')
    op.drop_column('quotations', 'reference_number')
    op.drop_constraint('uq_leads_reference_number', 'leads', type_='unique')
    op.drop_column('leads', 'reference_number')
    op.drop_constraint('uq_deals_reference_number', 'deals', type_='unique')
    op.drop_column('deals', 'reference_number')
    op.drop_constraint('uq_customers_reference_number', 'customers', type_='unique')
    op.drop_column('customers', 'reference_number')

    op.execute("DROP SEQUENCE sales_order_seq")
    op.execute("DROP SEQUENCE quotation_seq")
    op.execute("DROP SEQUENCE lead_seq")
    op.execute("DROP SEQUENCE deal_seq")
    op.execute("DROP SEQUENCE customer_seq")
    # ### end Alembic commands ###
