"""add_inventory_and_procurement_core_models

Revision ID: b4d07413ba3d
Revises: cf162e92c888
Create Date: 2026-06-23 00:36:35.131658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4d07413ba3d'
down_revision: Union[str, Sequence[str], None] = 'cf162e92c888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_receipts',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchase_receipts_custom_attributes', 'purchase_receipts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('warehouses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_warehouses_custom_attributes', 'warehouses', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('assets',
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_purchase_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_custom_attributes', 'assets', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('purchase_receipt_items',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchase_receipt_items_custom_attributes', 'purchase_receipt_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('stock_balances',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'warehouse_id')
    )
    op.create_index('idx_stock_balances_custom_attributes', 'stock_balances', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('stock_ledger_entries',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('voucher_type', sa.String(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('qty_change', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_ledger_entries_custom_attributes', 'stock_ledger_entries', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_foreign_key('fk_departments_manager_id_users', 'departments', 'users', ['manager_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('instance_profiles', sa.Column('active_modules', sa.JSON(), nullable=True))
    
    # Custom PostgreSQL trigger function and trigger for stock balances auto-update
    op.execute("""
    CREATE OR REPLACE FUNCTION update_stock_balance() RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO stock_balances (item_id, warehouse_id, actual_qty)
        VALUES (NEW.item_id, NEW.warehouse_id, NEW.qty_change)
        ON CONFLICT (item_id, warehouse_id)
        DO UPDATE SET actual_qty = stock_balances.actual_qty + EXCLUDED.actual_qty;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trigger_update_stock
    AFTER INSERT ON stock_ledger_entries
    FOR EACH ROW
    EXECUTE FUNCTION update_stock_balance();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Custom PostgreSQL trigger and function cleanup
    op.execute("DROP TRIGGER IF EXISTS trigger_update_stock ON stock_ledger_entries;")
    op.execute("DROP FUNCTION IF EXISTS update_stock_balance();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance_profiles', 'active_modules')
    op.drop_constraint('fk_departments_manager_id_users', 'departments', type_='foreignkey')
    op.drop_index('idx_stock_ledger_entries_custom_attributes', table_name='stock_ledger_entries', postgresql_using='gin')
    op.drop_table('stock_ledger_entries')
    op.drop_index('idx_stock_balances_custom_attributes', table_name='stock_balances', postgresql_using='gin')
    op.drop_table('stock_balances')
    op.drop_index('idx_purchase_receipt_items_custom_attributes', table_name='purchase_receipt_items', postgresql_using='gin')
    op.drop_table('purchase_receipt_items')
    op.drop_index('idx_assets_custom_attributes', table_name='assets', postgresql_using='gin')
    op.drop_table('assets')
    op.drop_index('idx_warehouses_custom_attributes', table_name='warehouses', postgresql_using='gin')
    op.drop_table('warehouses')
    op.drop_index('idx_purchase_receipts_custom_attributes', table_name='purchase_receipts', postgresql_using='gin')
    op.drop_table('purchase_receipts')
    # ### end Alembic commands ###
