"""add_preferences_columns

Revision ID: b6c9bc022561
Revises: f3539a6bef33
Create Date: 2026-06-21 00:17:23.151484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c9bc022561'
down_revision: Union[str, Sequence[str], None] = 'f3539a6bef33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_profiles', sa.Column('default_preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('instance_profiles', 'default_preferences')
    # ### end Alembic commands ###
