"""Restructure organization table

Revision ID: b888f0c4779e
Revises: 063a4d300d6a
Create Date: 2026-07-13 12:37:07.139422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b888f0c4779e'
down_revision: Union[str, Sequence[str], None] = '063a4d300d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('company_name', sa.String(length=255), nullable=False, server_default='B-Core Nexus Org'))
    op.add_column('organizations', sa.Column('trading_name', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('registration_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('primary_industry', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('favicon_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('cin_number', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('official_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('street_address', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state_province', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('date_format', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('fiscal_year_start', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('number_format', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('default_bank_account_id', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('default_dispatch_warehouse_id', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('default_receiving_warehouse_id', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('standard_terms', sa.Text(), nullable=True))
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'primary_email')
    op.drop_column('organizations', 'legal_name')
    op.drop_column('organizations', 'name')
    op.drop_column('organizations', 'industry_vertical')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_workspace_string', 'user_workspaces', type_='unique')
    op.add_column('organizations', sa.Column('industry_vertical', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('legal_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('primary_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'standard_terms')
    op.drop_column('organizations', 'default_receiving_warehouse_id')
    op.drop_column('organizations', 'default_dispatch_warehouse_id')
    op.drop_column('organizations', 'default_bank_account_id')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'number_format')
    op.drop_column('organizations', 'fiscal_year_start')
    op.drop_column('organizations', 'date_format')
    op.drop_column('organizations', 'zip_code')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'state_province')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'street_address')
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'official_email')
    op.drop_column('organizations', 'cin_number')
    op.drop_column('organizations', 'favicon_url')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'primary_industry')
    op.drop_column('organizations', 'registration_date')
    op.drop_column('organizations', 'trading_name')
    op.drop_column('organizations', 'company_name')
    # ### end Alembic commands ###
