"""Add UniqueConstraint to RecordShare

Revision ID: b8a69636ef19
Revises: b97de362fec9
Create Date: 2026-07-09 21:57:04.161257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a69636ef19'
down_revision: Union[str, Sequence[str], None] = 'b97de362fec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_record_share', 'record_shares', ['entity_type', 'entity_id', 'shared_with_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_record_share', 'record_shares', type_='unique')
    # ### end Alembic commands ###
