"""add new user profile fields

Revision ID: bda31ccf17b0
Revises: 48a35c70a587
Create Date: 2026-07-09 17:31:14.770029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda31ccf17b0'
down_revision: Union[str, Sequence[str], None] = '48a35c70a587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('mobile_no', sa.String(), nullable=True))
    op.add_column('employee_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('employee_profiles', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('employee_profiles', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'bio')
    op.drop_column('employee_profiles', 'birth_date')
    op.drop_column('employee_profiles', 'gender')
    op.drop_column('employee_profiles', 'mobile_no')
    # ### end Alembic commands ###
