"""Add ItemGroup and relate to Item

Revision ID: cf162e92c888
Revises: b6c9bc022561
Create Date: 2026-06-22 23:31:49.629778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf162e92c888'
down_revision: Union[str, Sequence[str], None] = 'b6c9bc022561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['item_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_groups_custom_attributes', 'item_groups', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_item_groups_name'), 'item_groups', ['name'], unique=True)
    op.add_column('items', sa.Column('item_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_items_item_group_id', 'items', 'item_groups', ['item_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_items_item_group_id', 'items', type_='foreignkey')
    op.drop_column('items', 'item_group_id')
    op.drop_index(op.f('ix_item_groups_name'), table_name='item_groups')
    op.drop_index('idx_item_groups_custom_attributes', table_name='item_groups', postgresql_using='gin')
    op.drop_table('item_groups')
    # ### end Alembic commands ###
