"""Add CRM Phase A tables

Revision ID: d78f4fa8836d
Revises: dd8f113dc38d
Create Date: 2026-07-07 22:38:24.820826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd78f4fa8836d'
down_revision: Union[str, Sequence[str], None] = 'dd8f113dc38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contacts_custom_attributes', 'contacts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('customers',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_custom_attributes', 'customers', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('leads',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lead_type', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('pipeline_stage', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_custom_attributes', 'leads', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('customer_addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=False),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_addresses_custom_attributes', 'customer_addresses', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('customer_contact_links',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('role_at_customer', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_contact_links_custom_attributes', 'customer_contact_links', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('lead_activities',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_activities_custom_attributes', 'lead_activities', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('lead_attachments',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_attachments_custom_attributes', 'lead_attachments', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('lead_contact_links',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('role_at_lead', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_contact_links_custom_attributes', 'lead_contact_links', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('lead_tags',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_tags_custom_attributes', 'lead_tags', ['custom_attributes'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_lead_tags_custom_attributes', table_name='lead_tags', postgresql_using='gin')
    op.drop_table('lead_tags')
    op.drop_index('idx_lead_contact_links_custom_attributes', table_name='lead_contact_links', postgresql_using='gin')
    op.drop_table('lead_contact_links')
    op.drop_index('idx_lead_attachments_custom_attributes', table_name='lead_attachments', postgresql_using='gin')
    op.drop_table('lead_attachments')
    op.drop_index('idx_lead_activities_custom_attributes', table_name='lead_activities', postgresql_using='gin')
    op.drop_table('lead_activities')
    op.drop_index('idx_customer_contact_links_custom_attributes', table_name='customer_contact_links', postgresql_using='gin')
    op.drop_table('customer_contact_links')
    op.drop_index('idx_customer_addresses_custom_attributes', table_name='customer_addresses', postgresql_using='gin')
    op.drop_table('customer_addresses')
    op.drop_index('idx_leads_custom_attributes', table_name='leads', postgresql_using='gin')
    op.drop_table('leads')
    op.drop_index('idx_customers_custom_attributes', table_name='customers', postgresql_using='gin')
    op.drop_table('customers')
    op.drop_index('idx_contacts_custom_attributes', table_name='contacts', postgresql_using='gin')
    op.drop_table('contacts')
    # ### end Alembic commands ###
