"""add_advanced_inventory_and_procurement

Revision ID: e9dadb28356c
Revises: 5ad02b6e84fc
Create Date: 2026-06-25 00:46:58.234947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9dadb28356c'
down_revision: Union[str, Sequence[str], None] = '5ad02b6e84fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proc_purchase_receipts',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'Cancelled', name='proc_purchase_receipt_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_purchase_receipts_custom_attributes', 'proc_purchase_receipts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_batch_numbers',
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_batch_numbers_custom_attributes', 'inv_batch_numbers', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_batch_numbers_batch_id'), 'inv_batch_numbers', ['batch_id'], unique=True)
    op.create_index(op.f('ix_inv_batch_numbers_item_id'), 'inv_batch_numbers', ['item_id'], unique=False)
    op.create_table('inv_product_bundles',
    sa.Column('parent_item_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_product_bundles_custom_attributes', 'inv_product_bundles', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_product_bundles_parent_item_id'), 'inv_product_bundles', ['parent_item_id'], unique=True)
    op.create_table('inv_serial_numbers',
    sa.Column('serial_no', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('purchase_document_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_serial_numbers_custom_attributes', 'inv_serial_numbers', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_serial_numbers_item_id'), 'inv_serial_numbers', ['item_id'], unique=False)
    op.create_index(op.f('ix_inv_serial_numbers_serial_no'), 'inv_serial_numbers', ['serial_no'], unique=True)
    op.create_index(op.f('ix_inv_serial_numbers_warehouse_id'), 'inv_serial_numbers', ['warehouse_id'], unique=False)
    op.create_table('proc_purchase_receipt_items',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['proc_purchase_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proc_purchase_receipt_items_custom_attributes', 'proc_purchase_receipt_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_product_bundle_items',
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['inv_product_bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_product_bundle_items_custom_attributes', 'inv_product_bundle_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_product_bundle_items_bundle_id'), 'inv_product_bundle_items', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_inv_product_bundle_items_item_id'), 'inv_product_bundle_items', ['item_id'], unique=False)
    op.drop_index(op.f('idx_purchase_receipt_items_custom_attributes'), table_name='purchase_receipt_items', postgresql_using='gin')
    op.drop_table('purchase_receipt_items')
    op.drop_index(op.f('idx_purchase_receipts_custom_attributes'), table_name='purchase_receipts', postgresql_using='gin')
    op.drop_table('purchase_receipts')
    op.add_column('inv_stock_ledger', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.add_column('inv_stock_ledger', sa.Column('serial_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_inv_stock_ledger_batch_id'), 'inv_stock_ledger', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inv_stock_ledger_serial_id'), 'inv_stock_ledger', ['serial_id'], unique=False)
    op.create_foreign_key(None, 'inv_stock_ledger', 'inv_batch_numbers', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inv_stock_ledger', 'inv_serial_numbers', ['serial_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inv_stock_ledger', type_='foreignkey')
    op.drop_constraint(None, 'inv_stock_ledger', type_='foreignkey')
    op.drop_index(op.f('ix_inv_stock_ledger_serial_id'), table_name='inv_stock_ledger')
    op.drop_index(op.f('ix_inv_stock_ledger_batch_id'), table_name='inv_stock_ledger')
    op.drop_column('inv_stock_ledger', 'serial_id')
    op.drop_column('inv_stock_ledger', 'batch_id')
    op.create_table('purchase_receipt_items',
    sa.Column('receipt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('accepted_qty', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('purchase_receipt_items_item_id_fkey')),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], name=op.f('purchase_receipt_items_receipt_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('purchase_receipt_items_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_receipt_items_pkey'))
    )
    op.create_index(op.f('idx_purchase_receipt_items_custom_attributes'), 'purchase_receipt_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('purchase_receipts',
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receipt_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_receipts_pkey'))
    )
    op.create_index(op.f('idx_purchase_receipts_custom_attributes'), 'purchase_receipts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_inv_product_bundle_items_item_id'), table_name='inv_product_bundle_items')
    op.drop_index(op.f('ix_inv_product_bundle_items_bundle_id'), table_name='inv_product_bundle_items')
    op.drop_index('idx_inv_product_bundle_items_custom_attributes', table_name='inv_product_bundle_items', postgresql_using='gin')
    op.drop_table('inv_product_bundle_items')
    op.drop_index('idx_proc_purchase_receipt_items_custom_attributes', table_name='proc_purchase_receipt_items', postgresql_using='gin')
    op.drop_table('proc_purchase_receipt_items')
    op.drop_index(op.f('ix_inv_serial_numbers_warehouse_id'), table_name='inv_serial_numbers')
    op.drop_index(op.f('ix_inv_serial_numbers_serial_no'), table_name='inv_serial_numbers')
    op.drop_index(op.f('ix_inv_serial_numbers_item_id'), table_name='inv_serial_numbers')
    op.drop_index('idx_inv_serial_numbers_custom_attributes', table_name='inv_serial_numbers', postgresql_using='gin')
    op.drop_table('inv_serial_numbers')
    op.drop_index(op.f('ix_inv_product_bundles_parent_item_id'), table_name='inv_product_bundles')
    op.drop_index('idx_inv_product_bundles_custom_attributes', table_name='inv_product_bundles', postgresql_using='gin')
    op.drop_table('inv_product_bundles')
    op.drop_index(op.f('ix_inv_batch_numbers_item_id'), table_name='inv_batch_numbers')
    op.drop_index(op.f('ix_inv_batch_numbers_batch_id'), table_name='inv_batch_numbers')
    op.drop_index('idx_inv_batch_numbers_custom_attributes', table_name='inv_batch_numbers', postgresql_using='gin')
    op.drop_table('inv_batch_numbers')
    op.drop_index('idx_proc_purchase_receipts_custom_attributes', table_name='proc_purchase_receipts', postgresql_using='gin')
    op.drop_table('proc_purchase_receipts')
    # ### end Alembic commands ###
