"""true_production_baseline

Revision ID: edbe64fb812e
Revises: 
Create Date: 2026-06-08 15:45:55.383129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edbe64fb812e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_items_custom_attributes', 'catalog_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_catalog_items_sku'), 'catalog_items', ['sku'], unique=True)
    op.create_index(op.f('ix_catalog_items_title'), 'catalog_items', ['title'], unique=False)
    op.create_table('currencies',
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fractional_unit_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_currencies_custom_attributes', 'currencies', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_currencies_iso_code'), 'currencies', ['iso_code'], unique=True)
    op.create_table('directory_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_type', sa.Enum('CUSTOMER', 'VENDOR', 'SITE', name='profiletype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_directory_profiles_custom_attributes', 'directory_profiles', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_directory_profiles_name'), 'directory_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_directory_profiles_profile_type'), 'directory_profiles', ['profile_type'], unique=False)
    op.create_table('document_sequences',
    sa.Column('sequence_key', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('padding_length', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_sequences_custom_attributes', 'document_sequences', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_sequences_sequence_key'), 'document_sequences', ['sequence_key'], unique=True)
    op.create_table('entities',
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=True),
    sa.Column('entity_type', sa.Enum('CUSTOMER', 'VENDOR', 'BRANCH', 'WAREHOUSE', 'SUBSIDIARY', name='entity_type_enum'), nullable=False),
    sa.Column('tax_identifier', sa.String(), nullable=True),
    sa.Column('primary_billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_custom_attributes', 'entities', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('instance_profiles',
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('is_initialized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_instance_profiles_custom_attributes', 'instance_profiles', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('industry_vertical', sa.String(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organizations_custom_attributes', 'organizations', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('system_settings',
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('default_timezone', sa.String(), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_settings_custom_attributes', 'system_settings', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('tax_categories',
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_categories_custom_attributes', 'tax_categories', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tax_categories_category_name'), 'tax_categories', ['category_name'], unique=True)
    op.create_table('tax_regions',
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_regions_custom_attributes', 'tax_regions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tax_regions_region_name'), 'tax_regions', ['region_name'], unique=True)
    op.create_table('transactions',
    sa.Column('transaction_number', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_source', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_custom_attributes', 'transactions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_transactions_transaction_number'), 'transactions', ['transaction_number'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='fk_departments_manager_id_users', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_departments_custom_attributes', 'departments', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('exchange_rates',
    sa.Column('from_currency_code', sa.String(length=3), nullable=False),
    sa.Column('to_currency_code', sa.String(length=3), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('effective_from_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['from_currency_code'], ['currencies.iso_code'], ),
    sa.ForeignKeyConstraint(['to_currency_code'], ['currencies.iso_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exchange_rates_custom_attributes', 'exchange_rates', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('items',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('catalog_type', sa.String(), nullable=False),
    sa.Column('default_uom', sa.String(), nullable=False),
    sa.Column('tax_category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tax_category_id'], ['tax_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_custom_attributes', 'items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_items_barcode'), 'items', ['barcode'], unique=True)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    op.create_table('tax_rules',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tax_categories.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['tax_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_rules_region_category_effective', 'tax_rules', ['region_id', 'category_id', 'effective_from'], unique=True)
    op.create_table('workspaces',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspaces_custom_attributes', 'workspaces', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_workspaces_identifier'), 'workspaces', ['identifier'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_or_location_code', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_entries_custom_attributes', 'ledger_entries', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ledger_entries_account_or_location_code'), 'ledger_entries', ['account_or_location_code'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('invite_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_tier', sa.Integer(), nullable=False),
    sa.Column('functional_roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('clearance_level', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_custom_attributes', 'users', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=True)
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_logs_payload', 'event_logs', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_event_logs_entity_id'), 'event_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_logs_entity_type'), 'event_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_table('user_workspaces',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_string', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'workspace_string'),
    sa.UniqueConstraint('user_id', 'workspace_string', name='uq_user_workspace_string')
    )
    op.create_foreign_key(None, 'hr_employee_records', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ops_tasks', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ops_tasks', type_='foreignkey')
    op.drop_constraint(None, 'hr_employee_records', type_='foreignkey')
    op.drop_table('user_workspaces')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_id'), table_name='event_logs')
    op.drop_index('idx_event_logs_payload', table_name='event_logs', postgresql_using='gin')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_custom_attributes', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    op.drop_index(op.f('ix_ledger_entries_account_or_location_code'), table_name='ledger_entries')
    op.drop_index('idx_ledger_entries_custom_attributes', table_name='ledger_entries', postgresql_using='gin')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_workspaces_identifier'), table_name='workspaces')
    op.drop_index('idx_workspaces_custom_attributes', table_name='workspaces', postgresql_using='gin')
    op.drop_table('workspaces')
    op.drop_index('idx_tax_rules_region_category_effective', table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_barcode'), table_name='items')
    op.drop_index('idx_items_custom_attributes', table_name='items', postgresql_using='gin')
    op.drop_table('items')
    op.drop_index('idx_exchange_rates_custom_attributes', table_name='exchange_rates', postgresql_using='gin')
    op.drop_table('exchange_rates')
    op.drop_index('idx_departments_custom_attributes', table_name='departments', postgresql_using='gin')
    op.drop_table('departments')
    op.drop_index(op.f('ix_transactions_transaction_number'), table_name='transactions')
    op.drop_index('idx_transactions_custom_attributes', table_name='transactions', postgresql_using='gin')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_tax_regions_region_name'), table_name='tax_regions')
    op.drop_index('idx_tax_regions_custom_attributes', table_name='tax_regions', postgresql_using='gin')
    op.drop_table('tax_regions')
    op.drop_index(op.f('ix_tax_categories_category_name'), table_name='tax_categories')
    op.drop_index('idx_tax_categories_custom_attributes', table_name='tax_categories', postgresql_using='gin')
    op.drop_table('tax_categories')
    op.drop_index('idx_system_settings_custom_attributes', table_name='system_settings', postgresql_using='gin')
    op.drop_table('system_settings')
    op.drop_index('idx_organizations_custom_attributes', table_name='organizations', postgresql_using='gin')
    op.drop_table('organizations')
    op.drop_index('idx_instance_profiles_custom_attributes', table_name='instance_profiles', postgresql_using='gin')
    op.drop_table('instance_profiles')
    op.drop_index('idx_entities_custom_attributes', table_name='entities', postgresql_using='gin')
    op.drop_table('entities')
    op.drop_index(op.f('ix_document_sequences_sequence_key'), table_name='document_sequences')
    op.drop_index('idx_document_sequences_custom_attributes', table_name='document_sequences', postgresql_using='gin')
    op.drop_table('document_sequences')
    op.drop_index(op.f('ix_directory_profiles_profile_type'), table_name='directory_profiles')
    op.drop_index(op.f('ix_directory_profiles_name'), table_name='directory_profiles')
    op.drop_index('idx_directory_profiles_custom_attributes', table_name='directory_profiles', postgresql_using='gin')
    op.drop_table('directory_profiles')
    op.drop_index(op.f('ix_currencies_iso_code'), table_name='currencies')
    op.drop_index('idx_currencies_custom_attributes', table_name='currencies', postgresql_using='gin')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_catalog_items_title'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_sku'), table_name='catalog_items')
    op.drop_index('idx_catalog_items_custom_attributes', table_name='catalog_items', postgresql_using='gin')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
