"""true_production_baseline

Revision ID: f3539a6bef33
Revises: 
Create Date: 2026-06-08 15:53:20.429032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3539a6bef33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_items_custom_attributes', 'catalog_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_catalog_items_sku'), 'catalog_items', ['sku'], unique=True)
    op.create_index(op.f('ix_catalog_items_title'), 'catalog_items', ['title'], unique=False)
    op.create_table('crm_customers',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('LEAD', 'OPPORTUNITY', 'ACTIVE_CUSTOMER', 'INACTIVE', name='crm_customer_lifecycle_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_customers_custom_attributes', 'crm_customers', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_customers_company_name'), 'crm_customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_crm_customers_created_at'), 'crm_customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_customers_email'), 'crm_customers', ['email'], unique=True)
    op.create_table('currencies',
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fractional_unit_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_currencies_custom_attributes', 'currencies', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_currencies_iso_code'), 'currencies', ['iso_code'], unique=True)
    op.create_table('directory_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_type', sa.Enum('CUSTOMER', 'VENDOR', 'SITE', name='profiletype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_directory_profiles_custom_attributes', 'directory_profiles', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_directory_profiles_name'), 'directory_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_directory_profiles_profile_type'), 'directory_profiles', ['profile_type'], unique=False)
    op.create_table('document_sequences',
    sa.Column('sequence_key', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('padding_length', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_sequences_custom_attributes', 'document_sequences', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_sequences_sequence_key'), 'document_sequences', ['sequence_key'], unique=True)
    op.create_table('entities',
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=True),
    sa.Column('entity_type', sa.Enum('CUSTOMER', 'VENDOR', 'BRANCH', 'WAREHOUSE', 'SUBSIDIARY', name='entity_type_enum'), nullable=False),
    sa.Column('tax_identifier', sa.String(), nullable=True),
    sa.Column('primary_billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_custom_attributes', 'entities', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_accounts',
    sa.Column('account_code', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='fin_account_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_accounts_custom_attributes', 'fin_accounts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_fin_accounts_account_code'), 'fin_accounts', ['account_code'], unique=True)
    op.create_table('fin_journal_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', name='fin_journal_entry_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_journal_entries_custom_attributes', 'fin_journal_entries', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_fin_journal_entries_entry_date'), 'fin_journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_fin_journal_entries_reference_number'), 'fin_journal_entries', ['reference_number'], unique=True)
    op.create_table('instance_profiles',
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('is_initialized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_instance_profiles_custom_attributes', 'instance_profiles', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('inv_items',
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=False, comment='Unit of measure — e.g. Piece, Box, Kg, Litre'),
    sa.Column('item_group', sa.String(length=100), nullable=False, comment='Logical grouping — e.g. Raw Material, Finished Goods'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_items_custom_attributes', 'inv_items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_items_name'), 'inv_items', ['name'], unique=False)
    op.create_index(op.f('ix_inv_items_sku'), 'inv_items', ['sku'], unique=True)
    op.create_table('inv_warehouses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_warehouses_custom_attributes', 'inv_warehouses', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_warehouses_name'), 'inv_warehouses', ['name'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('industry_vertical', sa.String(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organizations_custom_attributes', 'organizations', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('system_settings',
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('default_timezone', sa.String(), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_settings_custom_attributes', 'system_settings', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('tax_categories',
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_categories_custom_attributes', 'tax_categories', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tax_categories_category_name'), 'tax_categories', ['category_name'], unique=True)
    op.create_table('tax_regions',
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_regions_custom_attributes', 'tax_regions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tax_regions_region_name'), 'tax_regions', ['region_name'], unique=True)
    op.create_table('transactions',
    sa.Column('transaction_number', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_source', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_custom_attributes', 'transactions', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_transactions_transaction_number'), 'transactions', ['transaction_number'], unique=True)
    op.create_table('crm_contacts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_contacts_custom_attributes', 'crm_contacts', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_contacts_customer_id'), 'crm_contacts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_email'), 'crm_contacts', ['email'], unique=False)
    op.create_table('crm_interaction_logs',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.Enum('CALL', 'EMAIL', 'MEETING', 'NOTE', name='crm_interaction_type'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('logged_by_user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_interaction_logs_custom_attributes', 'crm_interaction_logs', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_interaction_logs_customer_id'), 'crm_interaction_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_interaction_logs_logged_by_user_id'), 'crm_interaction_logs', ['logged_by_user_id'], unique=False)
    op.create_index(op.f('ix_crm_interaction_logs_timestamp'), 'crm_interaction_logs', ['timestamp'], unique=False)
    op.create_table('crm_quotations',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('quotation_reference', sa.String(length=100), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='crm_quotation_status'), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_quotations_custom_attributes', 'crm_quotations', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_quotations_customer_id'), 'crm_quotations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_quotations_quotation_date'), 'crm_quotations', ['quotation_date'], unique=False)
    op.create_index(op.f('ix_crm_quotations_quotation_reference'), 'crm_quotations', ['quotation_reference'], unique=True)
    op.create_table('crm_sales_orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_reference', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'FULFILLED', 'CANCELLED', name='crm_sales_order_status'), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_sales_orders_custom_attributes', 'crm_sales_orders', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_sales_orders_customer_id'), 'crm_sales_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_sales_orders_order_date'), 'crm_sales_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_crm_sales_orders_order_reference'), 'crm_sales_orders', ['order_reference'], unique=True)
    op.create_table('crm_tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='crm_task_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='crm_task_priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_tasks_custom_attributes', 'crm_tasks', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_tasks_assigned_user_id'), 'crm_tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_created_at'), 'crm_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_tasks_customer_id'), 'crm_tasks', ['customer_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='fk_departments_manager_id_users', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_departments_custom_attributes', 'departments', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('exchange_rates',
    sa.Column('from_currency_code', sa.String(length=3), nullable=False),
    sa.Column('to_currency_code', sa.String(length=3), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('effective_from_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['from_currency_code'], ['currencies.iso_code'], ),
    sa.ForeignKeyConstraint(['to_currency_code'], ['currencies.iso_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exchange_rates_custom_attributes', 'exchange_rates', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_table('fin_journal_entry_lines',
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['fin_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['fin_journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_journal_entry_lines_custom_attributes', 'fin_journal_entry_lines', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_fin_journal_entry_lines_account_id'), 'fin_journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_fin_journal_entry_lines_journal_entry_id'), 'fin_journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_table('inv_stock_ledger',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('qty_change', sa.Numeric(precision=18, scale=4), nullable=False, comment='Positive number — direction is determined by transaction_type'),
    sa.Column('transaction_type', sa.Enum('IN', 'OUT', name='inv_stock_transaction_type'), nullable=False),
    sa.Column('reference_note', sa.String(length=500), nullable=True, comment='Optional PO/SO number, batch ID, or free-text note'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_stock_ledger_custom_attributes', 'inv_stock_ledger', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inv_stock_ledger_item_id'), 'inv_stock_ledger', ['item_id'], unique=False)
    op.create_index(op.f('ix_inv_stock_ledger_timestamp'), 'inv_stock_ledger', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inv_stock_ledger_warehouse_id'), 'inv_stock_ledger', ['warehouse_id'], unique=False)
    op.create_table('items',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('catalog_type', sa.String(), nullable=False),
    sa.Column('default_uom', sa.String(), nullable=False),
    sa.Column('tax_category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tax_category_id'], ['tax_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_custom_attributes', 'items', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_items_barcode'), 'items', ['barcode'], unique=True)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    op.create_table('ops_projects',
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', name='ops_project_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ops_projects_custom_attributes', 'ops_projects', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ops_projects_customer_id'), 'ops_projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ops_projects_project_name'), 'ops_projects', ['project_name'], unique=False)
    op.create_table('tax_rules',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tax_categories.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['tax_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_rules_region_category_effective', 'tax_rules', ['region_id', 'category_id', 'effective_from'], unique=True)
    op.create_table('workspaces',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspaces_custom_attributes', 'workspaces', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_workspaces_identifier'), 'workspaces', ['identifier'], unique=True)
    op.create_table('crm_quotation_lines',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['crm_quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_quotation_lines_custom_attributes', 'crm_quotation_lines', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_quotation_lines_quotation_id'), 'crm_quotation_lines', ['quotation_id'], unique=False)
    op.create_table('crm_sales_order_lines',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['crm_sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_sales_order_lines_custom_attributes', 'crm_sales_order_lines', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crm_sales_order_lines_item_id'), 'crm_sales_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_crm_sales_order_lines_sales_order_id'), 'crm_sales_order_lines', ['sales_order_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_or_location_code', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_entries_custom_attributes', 'ledger_entries', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ledger_entries_account_or_location_code'), 'ledger_entries', ['account_or_location_code'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('invite_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_tier', sa.Integer(), nullable=False),
    sa.Column('functional_roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('clearance_level', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_custom_attributes', 'users', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=True)
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_logs_payload', 'event_logs', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_event_logs_entity_id'), 'event_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_logs_entity_type'), 'event_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_table('hr_employee_records',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'TERMINATED', name='hr_employment_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hr_employee_records_custom_attributes', 'hr_employee_records', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_hr_employee_records_hire_date'), 'hr_employee_records', ['hire_date'], unique=False)
    op.create_index(op.f('ix_hr_employee_records_user_id'), 'hr_employee_records', ['user_id'], unique=False)
    op.create_table('ops_tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_title', sa.String(length=255), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', name='ops_task_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ops_task_priority'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ops_tasks_custom_attributes', 'ops_tasks', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ops_tasks_assigned_user_id'), 'ops_tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_ops_tasks_project_id'), 'ops_tasks', ['project_id'], unique=False)
    op.create_table('user_workspaces',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_string', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'workspace_string'),
    sa.UniqueConstraint('user_id', 'workspace_string', name='uq_user_workspace_string')
    )
    op.create_table('hr_leave_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('SICK', 'VACATION', 'UNPAID', name='hr_leave_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='hr_leave_approval_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hr_leave_requests_custom_attributes', 'hr_leave_requests', ['custom_attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_hr_leave_requests_employee_id'), 'hr_leave_requests', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_leave_requests_employee_id'), table_name='hr_leave_requests')
    op.drop_index('idx_hr_leave_requests_custom_attributes', table_name='hr_leave_requests', postgresql_using='gin')
    op.drop_table('hr_leave_requests')
    op.drop_table('user_workspaces')
    op.drop_index(op.f('ix_ops_tasks_project_id'), table_name='ops_tasks')
    op.drop_index(op.f('ix_ops_tasks_assigned_user_id'), table_name='ops_tasks')
    op.drop_index('idx_ops_tasks_custom_attributes', table_name='ops_tasks', postgresql_using='gin')
    op.drop_table('ops_tasks')
    op.drop_index(op.f('ix_hr_employee_records_user_id'), table_name='hr_employee_records')
    op.drop_index(op.f('ix_hr_employee_records_hire_date'), table_name='hr_employee_records')
    op.drop_index('idx_hr_employee_records_custom_attributes', table_name='hr_employee_records', postgresql_using='gin')
    op.drop_table('hr_employee_records')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_id'), table_name='event_logs')
    op.drop_index('idx_event_logs_payload', table_name='event_logs', postgresql_using='gin')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_custom_attributes', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    op.drop_index(op.f('ix_ledger_entries_account_or_location_code'), table_name='ledger_entries')
    op.drop_index('idx_ledger_entries_custom_attributes', table_name='ledger_entries', postgresql_using='gin')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_crm_sales_order_lines_sales_order_id'), table_name='crm_sales_order_lines')
    op.drop_index(op.f('ix_crm_sales_order_lines_item_id'), table_name='crm_sales_order_lines')
    op.drop_index('idx_crm_sales_order_lines_custom_attributes', table_name='crm_sales_order_lines', postgresql_using='gin')
    op.drop_table('crm_sales_order_lines')
    op.drop_index(op.f('ix_crm_quotation_lines_quotation_id'), table_name='crm_quotation_lines')
    op.drop_index('idx_crm_quotation_lines_custom_attributes', table_name='crm_quotation_lines', postgresql_using='gin')
    op.drop_table('crm_quotation_lines')
    op.drop_index(op.f('ix_workspaces_identifier'), table_name='workspaces')
    op.drop_index('idx_workspaces_custom_attributes', table_name='workspaces', postgresql_using='gin')
    op.drop_table('workspaces')
    op.drop_index('idx_tax_rules_region_category_effective', table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_ops_projects_project_name'), table_name='ops_projects')
    op.drop_index(op.f('ix_ops_projects_customer_id'), table_name='ops_projects')
    op.drop_index('idx_ops_projects_custom_attributes', table_name='ops_projects', postgresql_using='gin')
    op.drop_table('ops_projects')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_barcode'), table_name='items')
    op.drop_index('idx_items_custom_attributes', table_name='items', postgresql_using='gin')
    op.drop_table('items')
    op.drop_index(op.f('ix_inv_stock_ledger_warehouse_id'), table_name='inv_stock_ledger')
    op.drop_index(op.f('ix_inv_stock_ledger_timestamp'), table_name='inv_stock_ledger')
    op.drop_index(op.f('ix_inv_stock_ledger_item_id'), table_name='inv_stock_ledger')
    op.drop_index('idx_inv_stock_ledger_custom_attributes', table_name='inv_stock_ledger', postgresql_using='gin')
    op.drop_table('inv_stock_ledger')
    op.drop_index(op.f('ix_fin_journal_entry_lines_journal_entry_id'), table_name='fin_journal_entry_lines')
    op.drop_index(op.f('ix_fin_journal_entry_lines_account_id'), table_name='fin_journal_entry_lines')
    op.drop_index('idx_fin_journal_entry_lines_custom_attributes', table_name='fin_journal_entry_lines', postgresql_using='gin')
    op.drop_table('fin_journal_entry_lines')
    op.drop_index('idx_exchange_rates_custom_attributes', table_name='exchange_rates', postgresql_using='gin')
    op.drop_table('exchange_rates')
    op.drop_index('idx_departments_custom_attributes', table_name='departments', postgresql_using='gin')
    op.drop_table('departments')
    op.drop_index(op.f('ix_crm_tasks_customer_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_created_at'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_assigned_user_id'), table_name='crm_tasks')
    op.drop_index('idx_crm_tasks_custom_attributes', table_name='crm_tasks', postgresql_using='gin')
    op.drop_table('crm_tasks')
    op.drop_index(op.f('ix_crm_sales_orders_order_reference'), table_name='crm_sales_orders')
    op.drop_index(op.f('ix_crm_sales_orders_order_date'), table_name='crm_sales_orders')
    op.drop_index(op.f('ix_crm_sales_orders_customer_id'), table_name='crm_sales_orders')
    op.drop_index('idx_crm_sales_orders_custom_attributes', table_name='crm_sales_orders', postgresql_using='gin')
    op.drop_table('crm_sales_orders')
    op.drop_index(op.f('ix_crm_quotations_quotation_reference'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_quotation_date'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_customer_id'), table_name='crm_quotations')
    op.drop_index('idx_crm_quotations_custom_attributes', table_name='crm_quotations', postgresql_using='gin')
    op.drop_table('crm_quotations')
    op.drop_index(op.f('ix_crm_interaction_logs_timestamp'), table_name='crm_interaction_logs')
    op.drop_index(op.f('ix_crm_interaction_logs_logged_by_user_id'), table_name='crm_interaction_logs')
    op.drop_index(op.f('ix_crm_interaction_logs_customer_id'), table_name='crm_interaction_logs')
    op.drop_index('idx_crm_interaction_logs_custom_attributes', table_name='crm_interaction_logs', postgresql_using='gin')
    op.drop_table('crm_interaction_logs')
    op.drop_index(op.f('ix_crm_contacts_email'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_customer_id'), table_name='crm_contacts')
    op.drop_index('idx_crm_contacts_custom_attributes', table_name='crm_contacts', postgresql_using='gin')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_transactions_transaction_number'), table_name='transactions')
    op.drop_index('idx_transactions_custom_attributes', table_name='transactions', postgresql_using='gin')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_tax_regions_region_name'), table_name='tax_regions')
    op.drop_index('idx_tax_regions_custom_attributes', table_name='tax_regions', postgresql_using='gin')
    op.drop_table('tax_regions')
    op.drop_index(op.f('ix_tax_categories_category_name'), table_name='tax_categories')
    op.drop_index('idx_tax_categories_custom_attributes', table_name='tax_categories', postgresql_using='gin')
    op.drop_table('tax_categories')
    op.drop_index('idx_system_settings_custom_attributes', table_name='system_settings', postgresql_using='gin')
    op.drop_table('system_settings')
    op.drop_index('idx_organizations_custom_attributes', table_name='organizations', postgresql_using='gin')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_inv_warehouses_name'), table_name='inv_warehouses')
    op.drop_index('idx_inv_warehouses_custom_attributes', table_name='inv_warehouses', postgresql_using='gin')
    op.drop_table('inv_warehouses')
    op.drop_index(op.f('ix_inv_items_sku'), table_name='inv_items')
    op.drop_index(op.f('ix_inv_items_name'), table_name='inv_items')
    op.drop_index('idx_inv_items_custom_attributes', table_name='inv_items', postgresql_using='gin')
    op.drop_table('inv_items')
    op.drop_index('idx_instance_profiles_custom_attributes', table_name='instance_profiles', postgresql_using='gin')
    op.drop_table('instance_profiles')
    op.drop_index(op.f('ix_fin_journal_entries_reference_number'), table_name='fin_journal_entries')
    op.drop_index(op.f('ix_fin_journal_entries_entry_date'), table_name='fin_journal_entries')
    op.drop_index('idx_fin_journal_entries_custom_attributes', table_name='fin_journal_entries', postgresql_using='gin')
    op.drop_table('fin_journal_entries')
    op.drop_index(op.f('ix_fin_accounts_account_code'), table_name='fin_accounts')
    op.drop_index('idx_fin_accounts_custom_attributes', table_name='fin_accounts', postgresql_using='gin')
    op.drop_table('fin_accounts')
    op.drop_index('idx_entities_custom_attributes', table_name='entities', postgresql_using='gin')
    op.drop_table('entities')
    op.drop_index(op.f('ix_document_sequences_sequence_key'), table_name='document_sequences')
    op.drop_index('idx_document_sequences_custom_attributes', table_name='document_sequences', postgresql_using='gin')
    op.drop_table('document_sequences')
    op.drop_index(op.f('ix_directory_profiles_profile_type'), table_name='directory_profiles')
    op.drop_index(op.f('ix_directory_profiles_name'), table_name='directory_profiles')
    op.drop_index('idx_directory_profiles_custom_attributes', table_name='directory_profiles', postgresql_using='gin')
    op.drop_table('directory_profiles')
    op.drop_index(op.f('ix_currencies_iso_code'), table_name='currencies')
    op.drop_index('idx_currencies_custom_attributes', table_name='currencies', postgresql_using='gin')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_crm_customers_email'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_created_at'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_company_name'), table_name='crm_customers')
    op.drop_index('idx_crm_customers_custom_attributes', table_name='crm_customers', postgresql_using='gin')
    op.drop_table('crm_customers')
    op.drop_index(op.f('ix_catalog_items_title'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_sku'), table_name='catalog_items')
    op.drop_index('idx_catalog_items_custom_attributes', table_name='catalog_items', postgresql_using='gin')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
