"""Drop clearance level add designation

Revision ID: fa2505d60254
Revises: 06f6ef514d6d
Create Date: 2026-06-25 16:04:24.363401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2505d60254'
down_revision: Union[str, Sequence[str], None] = '06f6ef514d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('designation', sa.String(), nullable=True))
    op.drop_column('users', 'clearance_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clearance_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'designation')
    # ### end Alembic commands ###
